"""
Production FastAPI application for Dermatology Disease Classification.
Wraps the pre-trained Gaussian Naive Bayes model with rigorous validation,
CORS support, medical metadata, and prediction probabilities.
"""

import json
import logging
import os
from typing import Any, Dict, List
import joblib
import numpy as np
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, FileResponse

from schemas import (
    ClassProbability,
    DermatologyInputFeatures,
    HealthResponse,
    PredictionResponse,
)

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("dermatology_api")



from contextlib import asynccontextmanager

# Global model state
MODEL = None
METADATA = None

MODEL_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "model"))
MODEL_FILE = os.path.join(MODEL_DIR, "gaussian_nb.joblib")
METADATA_FILE = os.path.join(MODEL_DIR, "metadata.json")

DISCLAIMER_TEXT = (
    "Medical Disclaimer: This prediction is generated by a Machine Learning model (Gaussian Naive Bayes) "
    "for educational and clinical research assistance only. It does NOT constitute medical diagnosis or "
    "clinical advice. Always consult a qualified dermatologist or physician for clinical evaluation."
)

def init_resources():
    global MODEL, METADATA
    if MODEL is not None and METADATA is not None:
        return

    logger.info("Initializing Dermatology Disease Classification Service...")

    if not os.path.exists(MODEL_FILE):
        logger.error(f"Model file not found at {MODEL_FILE}. Please run model/train.py first.")
        raise RuntimeError(f"Model file not found: {MODEL_FILE}")

    if not os.path.exists(METADATA_FILE):
        logger.error(f"Metadata file not found at {METADATA_FILE}.")
        raise RuntimeError(f"Metadata file not found: {METADATA_FILE}")

    try:
        MODEL = joblib.load(MODEL_FILE)
        logger.info(f"Loaded trained Gaussian Naive Bayes model from {MODEL_FILE}")
    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        raise RuntimeError(f"Failed to load model: {e}")

    try:
        with open(METADATA_FILE, "r", encoding="utf-8") as f:
            METADATA = json.load(f)
        logger.info("Loaded dataset and feature metadata successfully.")
    except Exception as e:
        logger.error(f"Failed to load metadata: {e}")
        raise RuntimeError(f"Failed to load metadata: {e}")

@asynccontextmanager
async def lifespan(app: FastAPI):
    init_resources()
    yield

app = FastAPI(
    title="Dermatology Disease Classification API",
    description="Machine Learning service for erythemato-squamous dermatology disease classification.",
    version="1.0.0",
    lifespan=lifespan
)

# CORS setup
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Permissive for development and testing
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Also ensure immediate initialization if imported directly
try:
    init_resources()
except Exception as e:
    logger.warning(f"Immediate resource initialization deferred to lifespan: {e}")

FRONTEND_DIST = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "frontend", "dist"))

@app.get("/", tags=["General"])
def root():
    index_file = os.path.join(FRONTEND_DIST, "index.html")
    if os.path.exists(index_file):
        return FileResponse(index_file)
    return {
        "service": "Dermatology Disease Classification API",
        "status": "online",
        "docs_url": "/docs",
        "predict_endpoint": "/predict"
    }

@app.get("/api", tags=["General"])
def api_info():
    return {
        "service": "Dermatology Disease Classification API",
        "status": "online",
        "docs_url": "/docs",
        "predict_endpoint": "/predict"
    }

@app.get("/health", response_model=HealthResponse, tags=["General"])
@app.get("/api/health", response_model=HealthResponse, tags=["General"], include_in_schema=False)
def health_check():
    return HealthResponse(
        status="healthy" if MODEL is not None else "degraded",
        model_loaded=MODEL is not None,
        model_name=METADATA.get("model_name", "Gaussian Naive Bayes") if METADATA else "None",
        features_count=len(METADATA.get("features", [])) if METADATA else 0,
        classes_count=len(METADATA.get("disease_classes", {})) if METADATA else 0,
    )

@app.get("/metadata", tags=["Metadata"])
@app.get("/api/metadata", tags=["Metadata"], include_in_schema=False)
def get_metadata():
    """Returns feature definitions, categories, display names, and test presets."""
    if not METADATA:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="Metadata not loaded.")
    return METADATA

@app.post("/predict", response_model=PredictionResponse, tags=["Prediction"])
@app.post("/api/predict", response_model=PredictionResponse, tags=["Prediction"], include_in_schema=False)
def predict(features_input: DermatologyInputFeatures):
    """
    Accepts 33 dermatology clinical and histopathological attributes,
    validates the input, runs Gaussian Naive Bayes inference, and returns
    the predicted disease along with prediction probabilities.
    """
    if MODEL is None or METADATA is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Classification model is not currently loaded."
        )

    try:
        feature_order = METADATA["features"]
        input_dict = features_input.model_dump()

        # Build feature vector strictly preserving exact order
        feature_vector = []
        for feature_name in feature_order:
            if feature_name not in input_dict:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail=f"Missing required feature: '{feature_name}'"
                )
            val = input_dict[feature_name]
            feature_vector.append(val)

        # Convert to DataFrame preserving feature names
        import pandas as pd
        X_input = pd.DataFrame([feature_vector], columns=feature_order)

        # Model prediction
        predicted_class_id = int(MODEL.predict(X_input)[0])

        # Model probabilities
        proba_array = MODEL.predict_proba(X_input)[0]
        classes = MODEL.classes_

        probabilities_list: List[ClassProbability] = []
        disease_classes = METADATA["disease_classes"]

        for cls_id, prob in zip(classes, proba_array):
            cls_key = str(cls_id)
            info = disease_classes.get(cls_key, {
                "name": f"Disease Class {cls_id}",
                "icd_ref": "N/A",
                "description": "Information not available."
            })
            probabilities_list.append(ClassProbability(
                class_id=int(cls_id),
                disease_name=info["name"],
                icd_ref=info.get("icd_ref", "N/A"),
                probability=round(float(prob), 6),
                percentage=f"{float(prob) * 100:.2f}%"
            ))

        # Sort probabilities in descending order
        probabilities_list.sort(key=lambda x: x.probability, reverse=True)

        # Primary disease info
        primary_disease = disease_classes.get(str(predicted_class_id), {
            "name": f"Disease Class {predicted_class_id}",
            "icd_ref": "N/A",
            "description": "Classification result."
        })

        # Confidence is the probability of the predicted class
        pred_prob = float(proba_array[list(classes).index(predicted_class_id)])

        return PredictionResponse(
            status="success",
            predicted_class=predicted_class_id,
            disease_name=primary_disease["name"],
            icd_ref=primary_disease.get("icd_ref", "N/A"),
            description=primary_disease.get("description", ""),
            confidence=round(pred_prob, 4),
            confidence_percentage=f"{pred_prob * 100:.2f}%",
            probabilities=probabilities_list,
            features_submitted=len(feature_vector),
            disclaimer=DISCLAIMER_TEXT
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Inference error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred during prediction inference: {str(e)}"
        )

# Global error handler for unexpected errors
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Unhandled error handling request to {request.url.path}: {exc}", exc_info=True)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "Internal server error occurred. Please verify input data and server health."}
    )

# Mount frontend static build if available
from starlette.staticfiles import StaticFiles

FRONTEND_DIST = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "frontend", "dist"))
if os.path.exists(FRONTEND_DIST):
    logger.info(f"Serving built frontend from {FRONTEND_DIST}")
    app.mount("/", StaticFiles(directory=FRONTEND_DIST, html=True), name="frontend_ui")

